blueprint:
  name: MOES ESW-0ZAA-EU (TS0044) Multi-Button
  description: Automate actions for the MOES ESW-0ZAA-EU (TS0044) Multi-Button over Zigbee
  domain: automation
  input:
    moes_multibutton:
      name: Button Name
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_wkai4ga5
          model: TS0044
          multiple: false
    button_one_short_press:
      name: Single Press
      description: Action to run on button 1 (lower-left) single press
      default: []
      selector:
        action: {}
    button_one_double_press:
      name: Double Press
      description: Action to run on button 1 (lower-left) double press
      default: []
      selector:
        action: {}
    button_one_long_press:
      name: Long Press
      description: Action to run on button 1 (lower-left) long press
      default: []
      selector:
        action: {}
    button_two_short_press:
      name: Single Press
      description: Action to run on button 2 (lower-right) single press
      default: []
      selector:
        action: {}
    button_two_double_press:
      name: Double Press
      description: Action to run on button 2 (lower-right) double press
      default: []
      selector:
        action: {}
    button_two_long_press:
      name: Long Press
      description: Action to run on button 2 (lower-right) long press
      default: []
      selector:
        action: {}
    button_three_short_press:
      name: Single Press
      description: Action to run on button 3 (upper-right) single press
      default: []
      selector:
        action: {}
    button_three_double_press:
      name: Double Press
      description: Action to run on button 3 (upper-right) double press
      default: []
      selector:
        action: {}
    button_three_long_press:
      name: Long Press
      description: Action to run on button 3 (upper-right) long press
      default: []
      selector:
        action: {}
    button_four_short_press:
      name: Single Press
      description: Action to run on button 4 (upper-left) single press
      default: []
      selector:
        action: {}
    button_four_double_press:
      name: Double Press
      description: Action to run on button 4 (upper-left) double press
      default: []
      selector:
        action: {}
    button_four_long_press:
      name: Long Press
      description: Action to run on button 4 (upper-left) long press
      default: []
      selector:
        action: {}
  source_url: https://github.com/cweinhofer/blueprints/blob/main/moes_esw-0zaa-eu_zha.yaml
mode: restart
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input moes_multibutton
action:
- variables:
    command: '{{ trigger.event.data.command }}'
    endpoint_id: '{{ trigger.event.data.endpoint_id }}'
- choose:
  - conditions: '{{ command == ''remote_button_short_press'' }}'
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input button_one_short_press
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input button_two_short_press
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input button_three_short_press
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input button_four_short_press
  - conditions: '{{ command == ''remote_button_double_press'' }}'
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input button_one_double_press
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input button_two_double_press
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input button_three_double_press
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input button_four_double_press
  - conditions: '{{ command == ''remote_button_long_press'' }}'
    sequence:
    - choose:
      - conditions: '{{ endpoint_id == 1 }}'
        sequence: !input button_one_long_press
      - conditions: '{{ endpoint_id == 2 }}'
        sequence: !input button_two_long_press
      - conditions: '{{ endpoint_id == 3 }}'
        sequence: !input button_three_long_press
      - conditions: '{{ endpoint_id == 4 }}'
        sequence: !input button_four_long_press
